{% set version = "0.19.0" %}

package:
  name: fief-client-fastapi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fief-client/fief_client-{{ version }}.tar.gz
  sha256: 3c310e92d74df9462bbaf0012b90f985f2f351d002d66051b95a95e731c85eb7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - flit >=3.2,<4
  run:
    - python >=3.7
    - httpx >=0.21.3,<0.24.0
    - jwcrypto =1.3.1
    - typing_extensions >=4.0.1
    - fastapi
    - makefun >=1.14.0,<2.0.0

test:
  imports:
    - fief_client

about:
  home: https://github.com/fief-dev/fief-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fief client for FastAPI
  doc_url: https://docs.fief.dev/integrate/python/fastapi
  dev_url: https://github.com/fief-dev/fief-python

extra:
  recipe-maintainers:
    - davidbrochart
