{% set version = "0.20.0" %}

package:
  name: fief-client-fastapi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fief-client/fief_client-{{ version }}.tar.gz
  sha256: dbfb906d03c4a5402ceac5c843aa4708535fb6f5d5c1c4e263ec06fbbbc434d7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - httpx >=0.21.3,<0.28.0
    - jwcrypto >=1.4,<2.0.0
    - typing_extensions >=4.0.1
    - fastapi
    - makefun >=1.14.0,<2.0.0

test:
  imports:
    - fief_client

about:
  home: https://github.com/fief-dev/fief-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fief client for FastAPI
  doc_url: https://docs.fief.dev/integrate/python/fastapi
  dev_url: https://github.com/fief-dev/fief-python

extra:
  recipe-maintainers:
    - davidbrochart
